# Generated by Django 2.2.1 on 2019-05-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='benchmarker',
        ),
    ]
