# Generated by Django 2.2.1 on 2019-06-10 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20190610_1608'),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authentication.Team', verbose_name='チーム'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BenchQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=100, verbose_name='ノード')),
                ('target_hostname', models.CharField(max_length=100, verbose_name='対象ホスト名')),
                ('target_ip', models.CharField(max_length=100, verbose_name='対象IPアドレス')),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('running', 'running'), ('done', 'done'), ('aborted', 'aborted'), ('canceled', 'canceled')], default='waiting', max_length=100, verbose_name='進捗')),
                ('is_passed', models.BooleanField(default=False, verbose_name='正答フラグ')),
                ('score', models.IntegerField(default=0, verbose_name='獲得スコア')),
                ('result_json', models.TextField(verbose_name='結果JSON')),
                ('log_text', models.TextField(verbose_name='ログ文字列')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Team', verbose_name='チーム')),
            ],
            options={
                'verbose_name': 'ベンチキュー',
                'verbose_name_plural': 'ベンチキュー',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contest.BenchQueue', verbose_name='ベンチキュー'),
        ),
    ]
