# Generated by Django 2.2.1 on 2019-06-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20190606_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benchqueue',
            old_name='progress',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='benchqueue',
            name='result',
        ),
        migrations.AddField(
            model_name='benchqueue',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='正答フラグ'),
        ),
    ]
