# Generated by Django 2.2.1 on 2019-06-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20190610_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_score', models.IntegerField(default=0, verbose_name='ベストスコア')),
                ('latest_score', models.IntegerField(default=0, verbose_name='最新獲得スコア')),
                ('latest_status', models.BooleanField(default=False, verbose_name='最新ベンチステータス')),
            ],
            options={
                'verbose_name': '集計スコア',
                'verbose_name_plural': '集計スコア',
            },
        ),
    ]
