# Generated by Django 2.2.1 on 2019-06-07 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20190607_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benchqueue',
            old_name='log_raw',
            new_name='log_text',
        ),
        migrations.RenameField(
            model_name='benchqueue',
            old_name='result_raw',
            new_name='result_json',
        ),
    ]
