# Generated by Django 2.2.2 on 2019-06-24 07:00

from django.db import migrations, models
import isucon.portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20190621_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='本文')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
            },
            bases=(isucon.portal.models.LogicalDeleteMixin, models.Model),
        ),
    ]
