# Generated by Django 2.2.2 on 2019-06-25 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_information'),
        ('contest', '0004_auto_20190625_1005'),
    ]

    operations = [
    ]
