# Generated by Django 2.2.1 on 2019-08-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20190809_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='reason',
            field=models.TextField(blank=True, verbose_name='結果メッセージ'),
        ),
    ]
