# Generated by Django 2.2.1 on 2019-08-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='latest_scored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最新スコア日時'),
        ),
    ]
