# Generated by Django 2.2.1 on 2019-08-29 04:13

from django.db import migrations, models
import isucon.portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_score_latest_scored_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='allowed_participate_at',
            field=isucon.portal.models.CommaSeparatedDateField(default='', max_length=512, verbose_name='対象日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='is_enabled',
            field=models.BooleanField(blank=True, default=False, verbose_name='表示'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='タイトル'),
            preserve_default=False,
        ),
    ]
