# Generated by Django 2.2.4 on 2019-08-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_auto_20190829_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score_history_json',
            field=models.TextField(blank=True, null=True, verbose_name='スコア履歴のJSONダンプ'),
        ),
    ]
