# Generated by Django 2.2.1 on 2019-08-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_auto_20190829_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='確定時刻'),
        ),
        migrations.DeleteModel(
            name='ScoreHistory',
        ),
    ]
