# Generated by Django 2.2.1 on 2019-09-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0014_auto_20190905_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='target_ip',
            field=models.CharField(default='', max_length=100, blank=True, verbose_name='対象サーバIPアドレス'),
            preserve_default=False,
        ),
    ]
