# Generated by Django 2.2.4 on 2019-09-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_job_target_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='best_scored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ベストスコア日時'),
        ),
    ]
