# Generated by Django 2.2.1 on 2019-09-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0016_score_best_scored_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ('-latest_score', '-best_score', '-best_scored_at', 'team'), 'verbose_name': 'チームスコア', 'verbose_name_plural': 'チームスコア'},
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(max_length=100, verbose_name='ホスト名'),
        ),
    ]
