version: '3.7'

services:
  django:
    restart: always
    build: ./
    depends_on:
      - postgres
    environment:
      - DJANGO_DATABASE_TYPE=postgres
    volumes:
      - "staticdata:/opt/app/static/"
  postgres:
    restart: always
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=isucon
      - POSTGRES_USER=isucon
      - POSTGRES_PASSWORD=password
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  nginx:
    restart: always
    image: nginx:latest
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf.d/:/etc/nginx/conf.d"
      - "staticdata:/opt/app/static/"
volumes:
  dbdata:
  staticdata:
