version: '3'

services:
  django:
    restart: always
    build: ./
    depends_on:
      - postgres
    environment:
      - DJANGO_DATABASE_TYPE=postgres
      - GITHUB_KEY
      - GITHUB_SECRET
      - DJANGO_ALLOWED_HOST
      - DJANGO_DEBUG
      - SLACK_ENDPOINT_URL
    volumes:
      - "staticdata:/opt/app/static/"
      - "mediadata:/opt/app/media/"
  discard_forever:
    restart: always
    build: ./
    depends_on:
      - django
    environment:
      - DJANGO_DATABASE_TYPE=postgres
    command: python manage.py discard_forever
  postgres:
    restart: always
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=isucon
      - POSTGRES_USER=isucon
      - POSTGRES_PASSWORD=password
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  nginx:
    restart: always
    image: nginx:latest
    depends_on:
      - django
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf.d/:/etc/nginx/conf.d"
      - "staticdata:/opt/app/static/"
      - "mediadata:/opt/app/media/"
volumes:
  dbdata:
  staticdata:
  mediadata:
