# Generated by Django 2.2.1 on 2019-08-14 05:55

from django.db import migrations, models
import isucon.portal.contest.alibaba.models
import isucon.portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='イメージID')),
                ('name', models.CharField(max_length=512, verbose_name='名前')),
                ('is_enabled', models.BooleanField(blank=True, verbose_name='共有有効')),
                ('allowed_participate_at', isucon.portal.contest.alibaba.models.CommaSeparatedDateField(max_length=512, verbose_name='共有対象日')),
            ],
            options={
                'ordering': ('id',),
            },
            bases=(isucon.portal.models.LogicalDeleteMixin, models.Model),
        ),
    ]
