# Generated by Django 2.2.1 on 2019-05-31 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='benchmarker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contest.Benchmarker', verbose_name='ベンチマーカー'),
        ),
    ]
