# Generated by Django 2.2.1 on 2019-05-31 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190531_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='benchmarker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.Benchmarker', verbose_name='ベンチマーカー'),
        ),
    ]
