# Generated by Django 2.2.1 on 2019-06-03 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20190531_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='benchmarker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contest.Benchmarker', verbose_name='ベンチマーカー'),
        ),
    ]
