# Generated by Django 2.2.1 on 2019-06-03 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20190603_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='benchmarker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.Benchmarker', verbose_name='ベンチマーカー'),
        ),
    ]
