# Generated by Django 2.2.1 on 2019-06-19 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_aggregatedscore'),
        ('authentication', '0006_auto_20190603_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='aggregated_score',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contest.AggregatedScore'),
            preserve_default=False,
        ),
    ]
