# Generated by Django 2.2.2 on 2019-06-21 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20190621_1742'),
        ('authentication', '0006_auto_20190603_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='aggregated_score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.AggregatedScore'),
        ),
    ]
