# Generated by Django 2.2.2 on 2019-06-21 07:54

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20190603_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='media/icons/'),
        ),
    ]
