# Generated by Django 2.2.2 on 2019-06-25 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_is_student'),
        ('authentication', '0009_auto_20190624_1748'),
    ]

    operations = [
    ]
