# Generated by Django 2.2.2 on 2019-06-25 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_merge_20190625_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='participate_at',
            field=models.DateField(blank=True, default=datetime.date(2019, 6, 25), verbose_name='参加日'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(blank=True, default=False, verbose_name='学生フラグ'),
        ),
    ]
