# Generated by Django 2.2.1 on 2019-08-05 07:26

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20190709_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='alibaba_account',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Alibaba Cloud Account ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
