# Generated by Django 2.2.1 on 2019-08-16 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20190805_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='aggregated_score',
        ),
    ]
