apiVersion: v1
kind: Service
metadata:
  name: portal-redis
spec:
  ports:
  - port: 6379
  selector:
    app: portal-redis

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: portal-redis
spec:
  selector:
    matchLabels:
      app: portal-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: portal-redis
    spec:
      containers:
      - image: redis:5.0-alpine
        name: portal-redis
        ports:
        - containerPort: 6379
          name: portal-redis
