apiVersion: v1
kind: Service
metadata:
  name: portal-db
spec:
  ports:
  - port: 5432
  selector:
    app: portal-db

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: portal-db
spec:
  selector:
    matchLabels:
      app: portal-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: portal-db
    spec:
      containers:
      - image: postgres:12-alpine
        name: portal-db
        env:
        - name: POSTGRES_DB
          value: isucon
        - name: POSTGRES_USER
          value: isucon
        - name: POSTGRES_PASSWORD
          value: password
        ports:
        - containerPort: 5432
          name: portal-db
        volumeMounts:
        - name: postgress-volume
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgress-volume
        hostPath:
          path: /opt/portal/data/postgresql
