kind: PersistentVolume
apiVersion: v1
metadata:
  name: portal-static-volume
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/portal/data/static

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: portal-static-nginx-volume
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/portal/data/static

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: portal-media-volume
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/portal/data/media

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: portal-media-nginx-volume
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/portal/data/media
