apiVersion: v1
kind: Service
metadata:
  name: portal-nginx
spec:
  type: NodePort
  ports:
    - name: "http-port"
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: portal-nginx

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: portal-nginx
spec:
  selector:
    matchLabels:
      app: portal-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: portal-nginx
    spec:
      containers:
      - image: isucon/portal-nginx:latest
        imagePullPolicy: IfNotPresent
        name: portal-nginx
        ports:
        - containerPort: 80
          name: portal-nginx
        volumeMounts:
        - name: static-volume
          mountPath: /opt/app/static
        - name: media-volume
          mountPath: /opt/app/media
        - name: log-volume
          mountPath: /var/log/nginx/

      volumes:
      - name: static-volume
        hostPath:
          path: /opt/portal/data/static
      - name: media-volume
        hostPath:
          path: /opt/portal/data/media
      - name: log-volume
        hostPath:
          path: /opt/portal/logs/nginx
