# Generated by Django 2.2.1 on 2019-05-31 08:18

from django.db import migrations, models
import django.db.models.deletion
import isucon.portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_team_benchmarker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='得点')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.Team', verbose_name='チーム')),
            ],
            options={
                'verbose_name': 'スコア履歴',
                'verbose_name_plural': 'スコア履歴',
            },
            bases=(isucon.portal.models.LogicalDeleteMixin, models.Model),
        ),
    ]
