# Generated by Django 2.2.1 on 2019-05-31 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorehistory',
            options={'ordering': ('-created_at',), 'verbose_name': 'スコア履歴', 'verbose_name_plural': 'スコア履歴'},
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 5, 31, 17, 51, 39, 612982), verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='正答フラグ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最終更新日時'),
        ),
    ]
