# Generated by Django 2.2.1 on 2019-05-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20190531_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorehistory',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='正答フラグ'),
        ),
    ]
